# -*- coding: utf-8 -*-
"""Every review Kat has, copied word for word (spelling and all) from Add to Event and Google.
Add to Event: (name, 'Mon YYYY', title or None, [paragraphs], tags). Google: (name, 'Mon YYYY', [paragraphs], tags).
Tags drive the filter buttons on reviews.html: kids, wedding, events, grownups."""

ATE_URL = 'https://www.addtoevent.co.uk/suppliers/the-painting-pixie-ltd'
GOOGLE_URL = 'https://www.google.com/search?q=The+Painting+Pixie+Ltd+Horsham+reviews'

ATE = [
 ("Bethany S", "Aug 2026", None, ["Absolutely amazing face painter! She came to my son’s birthday party and was brilliant with all the children. The children absolutely loved choosing their designs and were so excited with the finished results. She was professional, reliable and added such a lovely touch to the party. I would definitely recommend her to anyone looking for a face painter for a children’s party. Thank you so much! ⭐️⭐️⭐️⭐️⭐️"], "kids"),
 ("Olivia W", "Jul 2026", "Brilliant.", ["We used cat for our wedding to entertain kids- she was so good, the kids absolutely loved it and the balloons are great. Thanks cat. Would definitely use again."], "wedding"),
 ("Louise R", "Jun 2026", "Kat is amazing, book her with Confidence", ["Kat was fantastic, great communication, great service and fair price. her facepaint was exceptional and everyone commented that is was some of the best they have seen. thanks so much."], ""),
 ("Hina T", "Jan 2026", "Great service", ["We booked this face painter for our son’s first birthday and she was amazing. She was friendly, patient, and brilliant with the children, making everyone feel comfortable and included. The face painting was beautiful, creative, and done with great care using safe products.", "All the kids loved it, and even the parents were impressed! She really added something special to the party and helped make the day memorable for us all.", "I would highly recommend her for any children’s party and will definitely be booking again in the future."], "kids"),
 ("Tracie M", "May 2025", "AMAZING!!", ["Honestly couldn't have asked for a better service! The quality of Kats work was incredible, super friendly, amazing with the kids. Stayed for the whole duration. I honestly would recommend Kat over and over again. Her setup was impressive, so many things and colours too. Well done Kat, and thank you...again ♡ xx"], "kids"),
 ("Holly F", "Dec 2024", "Kat was amazing! 100% recommend, amazing valueu", ["Kat provided amazing face painting, each design was slightly different to match the features of each child. Prompt, polite, an artist with facepaints and just an overall lovely person. Would 100% recommend, amazing vaule for money."], "kids"),
 ("Lorella S", "Dec 2024", "Brilliant service", ["I had originally booked a lady who cancelled 4 days before the part I found this lady last minute and she was a great help, very professional great value for money and excellent detail I'm so glad that the lady I had cancelled last minute else we wouldn't have got Kat, the adults and kids ver very pleased."], "kids grownups"),
 ("Paul S", "Nov 2024", "Kat was fantastic!", ["A great artist who took the time and care to make sure all the kids had the design they wanted", "Turned up on time and worked past the time agreed", "Thank you so much for helping to make Lilly’s day special ❤️"], "kids"),
 ("Devika M", "Oct 2024", "Brilliant face painting and great with the kids", ["Kat was amazing! She was punctual, creative, fun and great with the children! Thanks so much for providing a great service for our corporate event."], "events"),
 ("Alanna B", "Oct 2024", "Incredible Artist - Fantastic Service", ["Kat was an fantastic addition to our event. Our festival themed party was brought to life with the addition of festival face paints. The Painting Pixie is an incredible artist and swiftly adapted their style to accommodate young butterflies and spidermen and grown-up glamour with some sparkling festival pieces."], "events grownups"),
 ("Amy B", "Sep 2024", "Outstanding!", ["Kat was amazing at our party - painting a huge number of adult and children’s faces with vibrant colours and designs - often taking cues from outfits to create designs that colour matched. I couldn’t recommend her more highly. We were all so reluctant to wash them off at the end of the day!!"], "grownups"),
 ("Marion G", "Sep 2024", "Happy kids!", ["Kat delivered really well - she was on time and ready to set our kids in a happy birthday mood! Very efficient, very talented. All around brilliant."], "kids"),
 ("Gill D", "Sep 2024", "Amazing!!!", ["Kat was absolutely fantastic. She managed to paint many of the children's faces quickly - her work / art work on the faces is top notch. I would highly recommend her and would definitely use her again", "Thank you Kat!"], "kids"),
 ("James H", "Aug 2024", "Kat was amazing! Thank you for coming along!", ["After having to find a last minute face painter for our Summer Fete, Kat stepped up and proved to be exceptionally popular with our guests on the day! Both professional and organised, I would strongly recommend The Painting Pixie for any family orientated party/fair!"], "events"),
 ("Mara S", "Aug 2024", "Loved the Painting Pixie!", ["We booked Kat for a 2h session for our company summer party and everyone loved her! The designs were all unique and really added to the happy, diverse vibe. Kat herself is super easy-going and professional. Arranging everything was very easy as well. Would 100% recommend!"], "events grownups"),
 ("Lisa K", "Jul 2024", "Amazing", ["Friendly and professional. They were very helpful and went through what we would like at the wedding reception. There ended up being a long queue at times just because they were so popular with both the kids and adults. At times there were people literally sprinting to get to her, it was amazing. All of the designs turned out wonderful. Highly recommend. If I could give more than the 5 stars, I would :)", "Attached photo was taken after hours of dancing, it stayed perfect and didn't stain the skin."], "wedding grownups"),
 ("Anne F", "Jul 2024", "Wonderful!", ["Kat was superb! Arrived on time, easy communication, lovely service, great with the kids, nice glitter & paint art. I would definitely recommend her!"], "kids"),
 ("Julie T", "Jul 2024", "Total professional, great service", ["Kat was great she arrived early and set up quickly. She is very calm and professional and happy to attempt anything the kids asked for, she is very fast which is great if you have a line of kids waiting! No hesitation in recommending and would happily book again. Also, of course, her skills are excellent, designs are beautiful!"], "kids"),
 ("Stuart A", "Jun 2024", "Excellent service", ["Kat arrived on time, was excellent both children and adults enjoyed some face painting and the tattoos. Thank you."], "kids grownups"),
 ("Sophia L", "May 2024", "incredible skill", ["Kat was absolutely fantastic! Her skill was incredible, as she was able to paint a variety of designs based on the children's requests and clothes. The kids had a blast. Additionally, she was extremely friendly and patient, giving each child and even adult individual attention. She added a special touch to the party, and our whole family was impressed with her work. Highly recommend!"], "kids"),
 ("Ninad D", "Apr 2024", "Superb service", ["Kat was very professional and prompt. The kids loved here face paintings and tattoos. She was very good with the kids and very easy to communicate with. Overall very happy with her services."], "kids"),
 ("Lynsey B", "Feb 2024", "Best activity ever, all kids enjoyed thank you", ["If you are looking for an activity 30 kids will enjoy, try this!! The amount of different face painting kat did was amazing. Kay even stayed a bit longer as when planning we didn’t think every child would want it, but we were wrong! I’ve never seen so many children wanting to do the same activity. Definitely booking again & several other parents there want to do the same!"], "kids"),
 ("Mahi S", "Feb 2024", "Fantastic service", ["Happy with her service"], ""),
 ("Sabii I", "Jan 2024", "Great service!! Kids loved it", ["It was a great service at my son's birthday party. All the kids fluttered to the artist and came back with amazing art.", "Super talented and so worth the money!!"], "kids"),
 ("Amaria A", "Jan 2024", "Fantastic face painting and service!", ["Kat was amazing! From receiving the quote to coordinating timings for the event, her communication was stellar. She showed up on time at the day of the event while other vendors ran late and was extremely patient waiting as we were running behind with getting her a table to do her setup. She was friendly and kind with all the guests and the girls loved their beautiful designs. I would highly recommend working with Kat! She also left everything so clean and was very sweet. Look forward to recommending and hiring her for future events."], "events"),
 ("Sarah D", "Dec 2023", "Excellent", ["Thank you"], ""),
 ("Martin L", "Dec 2023", "Fantastic designs!", ["Kat provided a brilliant service for my sons 4th Birthday party. Her designs were amazing and all the children were very happy. Even my son, who doesn’t normally like his face being painted loved his dinosaur face. She was also very good value for money so would definitely recommend."], "kids"),
 ("Kay M", "Nov 2023", "Fantastic service. Delighted!", ["Kat provided an exceptional service..", "She was a real highlight at our event..", "Busy and popular from the get go..", "Dealing with children brilliantly ..adults too..and most of our staff team!!!", "Professional .creative..and a bit of a genius!!", "Not only doing \"classic\" face paint options ..but free styling..in a hugely impressive way.", "Added lot of sparkle to our event!...", "I would not hesitate to recommend . And could not recommend more highly.", "Book! Because I am sure that this lady is about to become extremely busy ..sought after ..and booked up!"], "events grownups"),
 ("Ade S", "Nov 2023", "Fabulous service", ["Kat arrived early and had loads of cool designs for the kids. She was very patient with the kids. All the kids were very happy with the face paint. Some kids even went for seconds as they loved all the designs. I will definitely recommend her for your event. You won’t regret it."], "kids"),
 ("Emma J", "Oct 2023", "Great for what we needed!", ["Really easy to work with and efficient with communication etc"], "events"),
]

# Google Business Profile: 10 ratings, all 5 stars. 8 have written comments; 2 (Kristina S, Roxanne N, Oct 2026) are stars only.
GOOGLE = [
 ("Chantelle C", "Oct 2026", ["So cute. She's brilliant"], "kids"),
 ("Jamie D", "Oct 2026", ["Amazing face Painting really good with the kids"], "kids"),
 ("Daniel C", "Aug 2026", ["So amazing. Hired for our daughter's 4th and was phenomenal. Non stop and everyone was so complimentary of the amazing face paints! Thank you Kat!!!"], "kids"),
 ("Claire C", "Aug 2026", ["Amazing face painting! My son loved it!"], "kids"),
 ("Alessandra F", "Aug 2026", ["Great artwork! My daughters loved them"], "kids"),
 ("Rosemarie L", "Jul 2026", ["My son had he's face painted at a party and this lady was very good! He is deaf & she was polite and pointing for him to turn he's head rather than some would just shove hes face into a direction upsetting him so this was a big brownie point! Very artistic and finished of with lovely little details"], "kids"),
 ("James W", "Jul 2026", ["Kat came to our son's birthday party and she was great, the kids loved her and her designs were fantastic. Thanks Kat, we'll be booking you again next year ⭐"], "kids"),
 ("Emily A", "Jul 2026", ["Amazing lady! Done a fanatic job for 30 children! Would recommend fully"], "kids"),
]
GOOGLE_STAR_ONLY = 2
